ui <- fluidPage(
  introjsUI(),
  actionButton("help", "Walk-through"),
  tags$style(HTML("
    .tabbable > .nav > li > a[data-value='Overall survival'] {background-color: #99FFFF; color:gray}
    .tabbable > .nav > li > a[data-value='Disease-specific survival'] {background-color: #FF99FF; color:gray}
    .tabbable > .nav > li > a[data-value='Disease-free interval'] {background-color: #FFCCCC; color:gray}
    .tabbable > .nav > li > a[data-value='Progress-free interval'] {background-color: #CCFFCC; color:gray}
    .tabbable > .nav > li > a[data-value='Data table'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='Boxplot'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='CPH model'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='Forest plot'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='Schoenfeld plots'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='ROC'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='ANOVA'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='Validation'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='glmnet'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='BeSS'] {background-color: #eaecee; color:black}
    .tabbable > .nav > li > a[data-value='About'] {background-color: #FFFFCC; color:darkgray}
    .tabbable > .nav > li[class=active] > a {background-color: #6666FF; color:darkgray}
  ")),
  
  # Title
  titlePanel("SmulTCan"),
  
  # Sidebar
  sidebarLayout(
    sidebarPanel(
      introBox(fileInput("exp_file", "Upload Xena gene expression TSV file", accept = ".tsv"), data.step = 1,
                          data.intro = "For specifications of the input TSV file, refer to the Information page"),
      introBox(selectInput("dataset", "Dataset", datasets), data.step = 2, data.intro = "Select TCGA dataset you'd like analyze with your gene set"),
      introBox(sliderInput("n_genes", "# of genes", value = 0, min = 0, max = 20, step = 1), data.step = 3, 
                          data.intro = "Select the # of genes from your gene group that you'd like to analyze"),
      introBox(actionLink("selectall", "Select all genes in data"), data.step = 4, 
                          data.intro = "Click here (initially twice) if you'd like to analyze all genes in your set, but slider above should be at the max # of genes"),
      introBox(selectizeInput("genes", "Genes", NULL, multiple = TRUE), data.step = 5, 
                          data.intro = "Add/drop the genes from your gene set in this menu"),
      introBox(selectizeInput("fold_genes", "Fold change denominator", NULL, multiple = TRUE), data.step = 6, 
                                                              data.intro = "When you select a gene here, its expression value will be subtracted from the genes selected above"),
    ),
    
    # Main
    mainPanel(
      tabsetPanel(
        tabPanel("Data table",
          tabsetPanel(tabPanel("Overall survival", tableOutput("data_os"), downloadButton("data_os_down")),
                      tabPanel("Disease-specific survival", tableOutput("data_dss"), downloadButton("data_dss_down")),
                      tabPanel("Disease-free interval", tableOutput("data_dfi"), downloadButton("data_dfi_down")),
                      tabPanel("Progress-free interval", tableOutput("data_pfi"), downloadButton("data_pfi_down")))),
        tabPanel("Boxplot",
          tabsetPanel(tabPanel("Overall survival", plotOutput("data_box_os"), downloadButton("data_box_os_down")),
                      tabPanel("Disease-specific survival", plotOutput("data_box_dss"), downloadButton("data_box_dss_down")),
                      tabPanel("Disease-free interval", plotOutput("data_box_dfi"), downloadButton("data_box_dfi_down")),
                      tabPanel("Progress-free interval", plotOutput("data_box_pfi"), downloadButton("data_box_pfi_down")))),
        tabPanel("CPH model",  
          tabsetPanel(tabPanel("CPH coeffs",
                         tabsetPanel(tabPanel("Overall survival", plotOutput("pred_os"), downloadButton("pred_os_down")),
                                     tabPanel("Disease-specific survival", plotOutput("pred_dss"), downloadButton("pred_dss_down")),
                                     tabPanel("Disease-free interval", plotOutput("pred_dfi"), downloadButton("pred_dfi_down")),
                                     tabPanel("Progress-free interval", plotOutput("pred_pfi"), downloadButton("pred_pfi_down")))),
                      tabPanel("Coeffs",
                               tabsetPanel(tabPanel("Overall survival", tableOutput("coef_tab_os"), downloadButton("coef_tab_os_down")),
                                           tabPanel("Disease-specific survival", tableOutput("coef_tab_dss"), downloadButton("coef_tab_dss_down")),
                                           tabPanel("Disease-free interval", tableOutput("coef_tab_dfi"), downloadButton("coef_tab_dfi_down")),
                                           tabPanel("Progress-free interval", tableOutput("coef_tab_pfi"), downloadButton("coef_tab_pfi_down")))),
                      tabPanel("K-M", 
                        tabsetPanel(tabPanel("Overall survival", plotOutput("km_os"), downloadButton("km_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("km_dss"), downloadButton("km_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("km_dfi"), downloadButton("km_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("km_pfi"), downloadButton("km_pfi_down")))),
                      tabPanel("CumHz",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("cumhz_os"), downloadButton("cumhz_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("cumhz_dss"), downloadButton("cumhz_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("cumhz_dfi"), downloadButton("cumhz_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("cumhz_pfi"), downloadButton("cumhz_pfi_down")))),
                      tabPanel("PI data",
                        tabsetPanel(tabPanel("Overall survival", tableOutput("km_tab_os"), downloadButton("km_tab_os_down")),
                                    tabPanel("Disease-specific survival", tableOutput("km_tab_dss"), downloadButton("km_tab_dss_down")),
                                    tabPanel("Disease-free interval", tableOutput("km_tab_dfi"), downloadButton("km_tab_dfi_down")),
                                    tabPanel("Progress-free interval", tableOutput("km_tab_pfi"), downloadButton("km_tab_pfi_down")))),
                      tabPanel("Risk ROC",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("risk_roc_os"), downloadButton("risk_roc_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("risk_roc_dss"), downloadButton("risk_roc_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("risk_roc_dfi"), downloadButton("risk_roc_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("risk_roc_pfi"), downloadButton("risk_roc_pfi_down")))))),
        tabPanel("Forest plot",  
          tabsetPanel(tabPanel("Overall survival", plotOutput("forest_os"), downloadButton("forest_os_down")),
                      tabPanel("Disease-specific survival", plotOutput("forest_dss"), downloadButton("forest_dss_down")),
                      tabPanel("Disease-free interval", plotOutput("forest_dfi"), downloadButton("forest_dfi_down")),
                      tabPanel("Progress-free interval", plotOutput("forest_pfi"), downloadButton("forest_pfi_down")))),
        tabPanel("Schoenfeld plots",  
          tabsetPanel(tabPanel("Overall survival", plotOutput("schoen_os"), downloadButton("schoen_os_down")),
                      tabPanel("Disease-specific survival", plotOutput("schoen_dss"), downloadButton("schoen_dss_down")),
                      tabPanel("Disease-free interval", plotOutput("schoen_dfi"), downloadButton("schoen_dfi_down")),
                      tabPanel("Progress-free interval", plotOutput("schoen_pfi"), downloadButton("schoen_pfi_down")))),
        tabPanel("ROC",  
          tabsetPanel(tabPanel("Plot",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("roc_os"), downloadButton("roc_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("roc_dss"), downloadButton("roc_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("roc_dfi"), downloadButton("roc_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("roc_pfi"), downloadButton("roc_pfi_down")))),
                      tabPanel("Stats",
                        tabsetPanel(tabPanel("Overall survival", tableOutput("roc_data_os"), downloadButton("roc_data_os_down")),
                                    tabPanel("Disease-specific survival", tableOutput("roc_data_dss"), downloadButton("roc_data_dss_down")),
                                    tabPanel("Disease-free interval", tableOutput("roc_data_dfi"), downloadButton("roc_data_dfi_down")),
                                    tabPanel("Progress-free interval", tableOutput("roc_data_pfi"), downloadButton("roc_data_pfi_down")))))),
        tabPanel("ANOVA",
          tabsetPanel(tabPanel("Plot", 
                        tabsetPanel(tabPanel("Overall survival", plotOutput("anova_plot_os"), downloadButton("anova_plot_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("anova_plot_dss"), downloadButton("anova_plot_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("anova_plot_dfi"), downloadButton("anova_plot_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("anova_plot_pfi"), downloadButton("anova_plot_pfi_down")))),
                      tabPanel("Stats", 
                        tabsetPanel(tabPanel("Overall survival", tableOutput("anova_data_os"), downloadButton("anova_data_os_down")),
                                    tabPanel("Disease-specific survival", tableOutput("anova_data_dss"), downloadButton("anova_data_dss_down")),
                                    tabPanel("Disease-free interval", tableOutput("anova_data_dfi"), downloadButton("anova_data_dfi_down")),
                                    tabPanel("Progress-free interval", tableOutput("anova_data_pfi"), downloadButton("anova_data_pfi_down")))))),
        tabPanel("Validation",
          tabsetPanel(tabPanel("Plot",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("valid_plot_os"), downloadButton("valid_plot_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("valid_plot_dss"), downloadButton("valid_plot_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("valid_plot_dfi"), downloadButton("valid_plot_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("valid_plot_pfi"), downloadButton("valid_plot_pfi_down")))),
                      tabPanel("Stats",
                        tabsetPanel(tabPanel("Overall survival", tableOutput("valid_data_os"), downloadButton("valid_data_os_down")),
                                    tabPanel("Disease-specific survival", tableOutput("valid_data_dss"), downloadButton("valid_data_dss_down")),
                                    tabPanel("Disease-free interval", tableOutput("valid_data_dfi"), downloadButton("valid_data_dfi_down")),
                                    tabPanel("Progress-free interval", tableOutput("valid_data_pfi"), downloadButton("valid_data_pfi_down")))))),
        tabPanel("glmnet",
                sidebarLayout(
                     sidebarPanel(
                       selectInput("n_folds", "Folds", c("default", "sample_size")),
                       sliderInput("alph", "Elastic net", value = 1, min = 0, max = 1)
                ),
                mainPanel(
                     tabsetPanel(tabPanel("Plot",
                                          tabsetPanel(tabPanel("Overall survival", plotOutput("glm_pred_os"), downloadButton("glm_pred_os_down")),
                                                      tabPanel("Disease-specific survival", plotOutput("glm_pred_dss"), downloadButton("glm_pred_dss_down")),
                                                      tabPanel("Disease-free interval", plotOutput("glm_pred_dfi"), downloadButton("glm_pred_dfi_down")),
                                                      tabPanel("Progress-free interval", plotOutput("glm_pred_pfi"), downloadButton("glm_pred_pfi_down")))),
                                 tabPanel("Coeffs",
                                          tabsetPanel(tabPanel("Overall survival", tableOutput("glm_coef_tab_os"), downloadButton("glm_coef_tab_os_down")),
                                                      tabPanel("Disease-specific survival", tableOutput("glm_coef_tab_dss"), downloadButton("glm_coef_tab_dss_down")),
                                                      tabPanel("Disease-free interval", tableOutput("glm_coef_tab_dfi"), downloadButton("glm_coef_tab_dfi_down")),
                                                      tabPanel("Progress-free interval", tableOutput("glm_coef_tab_pfi"), downloadButton("glm_coef_tab_pfi_down")))),
                                 tabPanel("K-M", 
                                          tabsetPanel(tabPanel("Overall survival", plotOutput("glm_km_os"), downloadButton("glm_km_os_down")),
                                                      tabPanel("Disease-specific survival", plotOutput("glm_km_dss"), downloadButton("glm_km_dss_down")),
                                                      tabPanel("Disease-free interval", plotOutput("glm_km_dfi"), downloadButton("glm_km_dfi_down")),
                                                      tabPanel("Progress-free interval", plotOutput("glm_km_pfi"), downloadButton("glm_km_pfi_down")))),
                                 tabPanel("CumHz", 
                                          tabsetPanel(tabPanel("Overall survival", plotOutput("glm_cumhz_os"), downloadButton("glm_cumhz_os_down")),
                                                      tabPanel("Disease-specific survival", plotOutput("glm_cumhz_dss"), downloadButton("glm_cumhz_dss_down")),
                                                      tabPanel("Disease-free interval", plotOutput("glm_cumhz_dfi"), downloadButton("glm_cumhz_dfi_down")),
                                                      tabPanel("Progress-free interval", plotOutput("glm_cumhz_pfi"), downloadButton("glm_cumhz_pfi_down")))),
                                 tabPanel("PI data",
                                          tabsetPanel(tabPanel("Overall survival", tableOutput("glm_data_os"), downloadButton("glm_data_os_down")),
                                                      tabPanel("Disease-specific survival", tableOutput("glm_data_dss"), downloadButton("glm_data_dss_down")),
                                                      tabPanel("Disease-free interval", tableOutput("glm_data_dfi"), downloadButton("glm_data_dfi_down")),
                                                      tabPanel("Progress-free interval", tableOutput("glm_data_pfi"), downloadButton("glm_data_pfi_down")))),
                                 tabPanel("CV plot",
                                          tabsetPanel(tabPanel("Overall survival", plotOutput("glm_cv_os"), downloadButton("glm_cv_os_down")),
                                                      tabPanel("Disease-specific survival", plotOutput("glm_cv_dss"), downloadButton("glm_cv_dss_down")),
                                                      tabPanel("Disease-free interval", plotOutput("glm_cv_dfi"), downloadButton("glm_cv_dfi_down")),
                                                      tabPanel("Progress-free interval", plotOutput("glm_cv_pfi"), downloadButton("glm_cv_pfi_down")))),
                                 tabPanel("Risk ROC",
                                          tabsetPanel(tabPanel("Overall survival", plotOutput("glm_roc_os"), downloadButton("glm_roc_os_down")),
                                                      tabPanel("Disease-specific survival", plotOutput("glm_roc_dss"), downloadButton("glm_roc_dss_down")),
                                                      tabPanel("Disease-free interval", plotOutput("glm_roc_dfi"), downloadButton("glm_roc_dfi_down")),
                                                      tabPanel("Progress-free interval", plotOutput("glm_roc_pfi"), downloadButton("glm_roc_pfi_down"))))))
                )),
        tabPanel("BeSS",
          tabsetPanel(tabPanel("GIC",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("gic_os"), downloadButton("gic_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("gic_dss"), downloadButton("gic_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("gic_dfi"), downloadButton("gic_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("gic_pfi"), downloadButton("gic_pfi_down")))),
                      tabPanel("Plot",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("pred_bess_os"), downloadButton("pred_bess_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("pred_bess_dss"), downloadButton("pred_bess_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("pred_bess_dfi"), downloadButton("pred_bess_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("pred_bess_pfi"), downloadButton("pred_bess_pfi_down")))),
                      tabPanel("Coeffs",
                               tabsetPanel(tabPanel("Overall survival", tableOutput("bess_coef_tab_os"), downloadButton("bess_coef_tab_os_down")),
                                           tabPanel("Disease-specific survival", tableOutput("bess_coef_tab_dss"), downloadButton("bess_coef_tab_dss_down")),
                                           tabPanel("Disease-free interval", tableOutput("bess_coef_tab_dfi"), downloadButton("bess_coef_tab_dfi_down")),
                                           tabPanel("Progress-free interval", tableOutput("bess_coef_tab_pfi"), downloadButton("bess_coef_tab_pfi_down")))),
                      tabPanel("K-M",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("km_bess_os"), downloadButton("km_bess_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("km_bess_dss"), downloadButton("km_bess_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("km_bess_dfi"), downloadButton("km_bess_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("km_bess_pfi"), downloadButton("km_bess_pfi_down")))),
                      tabPanel("CumHz",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("bess_cumhz_os"), downloadButton("bess_cumhz_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("bess_cumhz_dss"), downloadButton("bess_cumhz_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("bess_cumhz_dfi"), downloadButton("bess_cumhz_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("bess_cumhz_pfi"), downloadButton("bess_cumhz_pfi_down")))),
                      tabPanel("PI data",
                        tabsetPanel(tabPanel("Overall survival", tableOutput("bess_data_os"), downloadButton("bess_data_os_down")),
                                    tabPanel("Disease-specific survival", tableOutput("bess_data_dss"), downloadButton("bess_data_dss_down")),
                                    tabPanel("Disease-free interval", tableOutput("bess_data_dfi"), downloadButton("bess_data_dfi_down")),
                                    tabPanel("Progress-free interval", tableOutput("bess_data_pfi"), downloadButton("bess_data_pfi_down")))),
                      tabPanel("Risk ROC",
                        tabsetPanel(tabPanel("Overall survival", plotOutput("bess_roc_os"), downloadButton("bess_roc_os_down")),
                                    tabPanel("Disease-specific survival", plotOutput("bess_roc_dss"), downloadButton("bess_roc_dss_down")),
                                    tabPanel("Disease-free interval", plotOutput("bess_roc_dfi"), downloadButton("bess_roc_dfi_down")),
                                    tabPanel("Progress-free interval", plotOutput("bess_roc_pfi"), downloadButton("bess_roc_pfi_down")))))),
        tabPanel("About", includeHTML("app_info/SmulTCan.html"))
        
      )
    )
  )
)



